import { FC } from 'react'

const Head: FC = () => {
  return (
    <>
      <title>Portfolio | Beshiimov</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/public/assets/icons/logo.ico" />
    </>
  )
}

export default Head
